# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170917_1850'),
        ('dormitories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitories',
            name='manager',
            field=models.ManyToManyField(related_name='manager', to='main.Employees', verbose_name='Заведующая'),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to='main.Employees', verbose_name='Старостат'),
        ),
    ]
