# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0002_auto_20170917_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitories',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Описание'),
        ),
    ]
