# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0004_auto_20170917_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitories',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Координаты'),
        ),
    ]
