# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('password_sha512', models.CharField(default='', max_length=200, verbose_name='SHA512 пароля')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Телефон')),
                ('institute', models.CharField(default='', max_length=100, verbose_name='Институт')),
                ('group', models.CharField(default='', max_length=20, verbose_name='Группа')),
                ('dormitory', models.IntegerField(default=1, verbose_name='Общежитие')),
                ('room', models.CharField(default='', max_length=20, verbose_name='Комната')),
                ('photo', models.FileField(upload_to='', verbose_name='Фотография')),
                ('status', models.BooleanField(default=False, verbose_name='Данные студента проверены')),
            ],
            options={
                'verbose_name': 'Студенты',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
