# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='show_student_unification',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу в меню "Полезная информация'),
        ),
    ]
