# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 19:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('address', ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Адрес')),
                ('link_instagram', models.CharField(default='', max_length=200, verbose_name='Ссылка на Instagram')),
                ('link_vk', models.CharField(default='', max_length=200, verbose_name='Ссылка на VK')),
                ('img_slide_1', models.FileField(upload_to='', verbose_name='Картинка слайда #1')),
                ('img_slide_2', models.FileField(upload_to='', verbose_name='Картинка слайда #2')),
                ('img_slide_3', models.FileField(upload_to='', verbose_name='Картинка слайда #3')),
                ('short_about', models.TextField(default='', max_length=200, verbose_name='Краткое описание')),
                ('count_news', models.IntegerField(default=6, verbose_name='Количество новостей на странице')),
                ('description_footer', models.TextField(default='', max_length=120, verbose_name='Описание в подвале сайта')),
                ('description_service', models.TextField(default='', max_length=1000, verbose_name='Описание страницы сервисов')),
                ('description_issues', models.TextField(default='', max_length=3000, verbose_name='Описание страницы приемной')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
