# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20170831_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='count_news',
            new_name='count_articles',
        ),
    ]
