# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20170831_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_service',
            field=models.BooleanField(default=True, verbose_name='Сервисы включены'),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_students',
            field=models.BooleanField(default=True, verbose_name='Авторизация/Регистрация включена'),
        ),
    ]
