# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_settings_enable_vr'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='count_students',
            field=models.IntegerField(default=0, verbose_name='Количество студентов'),
        ),
        migrations.AddField(
            model_name='settings',
            name='count_work',
            field=models.IntegerField(default=0, verbose_name='Количество работников'),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_count_data',
            field=models.BooleanField(default=False, verbose_name='Выводить реальные статические данные на главной странице'),
        ),
    ]
