# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20170908_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='img_slide_4',
            field=models.FileField(default='', upload_to='', verbose_name='Картинка слайда #4'),
            preserve_default=False,
        ),
    ]
