# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_settings_feedback_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='count_events',
            field=models.IntegerField(default=6, verbose_name='Количество мероприятий на странице'),
        ),
    ]
