# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 18:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_settings_count_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='description_issues',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='feedback_enable',
        ),
        migrations.AddField(
            model_name='settings',
            name='description_vr',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание страницы приемной'),
        ),
    ]
