# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20170913_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='img_slide_1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='img_slide_2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='img_slide_3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='img_slide_4',
        ),
    ]
