# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20170913_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='count_students',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='count_work',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='enable_count_data',
        ),
        migrations.AlterField(
            model_name='settings',
            name='enable_vr',
            field=models.BooleanField(default=True, verbose_name='Виртуальная приемная включена'),
        ),
    ]
