# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 21:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20170914_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description_student_council',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание страницы студсовет студгородка'),
        ),
    ]
