# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 14:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_settings_description_student_council'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='description_vr',
        ),
        migrations.AddField(
            model_name='settings',
            name='rules_vr',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Правила для приемной'),
        ),
    ]
