# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_auto_20170917_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='short_about',
        ),
        migrations.AddField(
            model_name='settings',
            name='description_short_about',
            field=models.TextField(default='', max_length=400, verbose_name='Описание сайта в подвале'),
        ),
    ]
