# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_auto_20170917_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='link_youtube',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на YouTube'),
        ),
    ]
