# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_settings_description_newspaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='description_service',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='enable_service',
        ),
    ]
