# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 17:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_auto_20171213_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description_newspaper',
            field=ckeditor.fields.RichTextField(default='', max_length=2000, verbose_name='Описание раздела Газета'),
        ),
    ]
