# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 18:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_auto_20171213_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description_student_council_dormitories',
            field=ckeditor.fields.RichTextField(default='', max_length=2000, verbose_name='Описание Старостата'),
        ),
    ]
