# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 17:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(max_length=2000, verbose_name='Описание')),
                ('img', models.FileField(upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='Координаты карты')),
                ('email_form', models.EmailField(max_length=100, verbose_name='Email формы обратной связи')),
                ('address', ckeditor.fields.RichTextField(max_length=200, verbose_name='Адрес')),
                ('phone', ckeditor.fields.RichTextField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email на страницу')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('post', models.CharField(default='', max_length=100, verbose_name='Должность')),
                ('description', models.TextField(default='', max_length=150, verbose_name='Описание обязанностей')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('photo', models.FileField(upload_to='', verbose_name='Фото')),
                ('type', models.BooleanField(default=False, verbose_name='Вывести на главную страницу')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('text', models.TextField(default='', max_length=300, verbose_name='Описание')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Локация')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('time_start', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('time_end', models.TimeField(default=django.utils.timezone.now, verbose_name='Время конца')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
