# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170909_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='vk',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка на VK(можно не заполнять)'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email(можно не заполнять)'),
        ),
    ]
