# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170909_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
