# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email(можно не заполнять)'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='vk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на VK(можно не заполнять)'),
        ),
    ]
