# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170910_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='show_main_page_status',
            field=models.BooleanField(default=False, verbose_name='Вывести на главную страницу'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.CharField(default='', max_length=200, verbose_name='Тип'),
        ),
    ]
