# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170917_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcouncil',
            old_name='employee',
            new_name='employees',
        ),
    ]
