# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170917_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=300, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Страница: Руководство',
                'verbose_name_plural': 'Страница: Руководство',
            },
        ),
        migrations.AlterModelOptions(
            name='studentcouncil',
            options={'verbose_name': 'Страница: Студсовет студгородка', 'verbose_name_plural': 'Страница: Студсовет студгородка'},
        ),
        migrations.AddField(
            model_name='employees',
            name='time_work',
            field=models.CharField(blank=True, max_length=300, verbose_name='Приемные часы'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='employees',
            field=models.ManyToManyField(to='main.Employees', verbose_name='Работники'),
        ),
    ]
