# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170917_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='leadership_status',
            field=models.BooleanField(default=False, verbose_name='Руководство'),
        ),
    ]
