# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_employees_leadership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.CharField(default='', max_length=400, verbose_name='Адрес'),
        ),
    ]
