# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 22:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_employees_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=150, verbose_name='Описание обязанностей'),
        ),
    ]
