# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_newspaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper',
            old_name='img',
            new_name='images',
        ),
    ]
