# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 07:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20171026_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=3000, verbose_name='Описание обязанностей'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='post',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
    ]
