# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20171107_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_link',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на кнпоке (Напрмер: contact, без домена сайта)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(default='', max_length=100, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Текст на слайде'),
        ),
    ]
