# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 16:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=3000, verbose_name='Описание'),
        ),
    ]
